version: 2

models:
  - name: int_customer_subscriptions
    description: "Modelo intermédio central que junta subscrições, clientes e carros, e calcula as métricas temporais e financeiras principais (ex: data de fim e valor total esperado)." 
    config:
      tags: ['intermediate', 'core']
    tests:
        - dbt_utils.expression_is_true:
            expression: "subscription_end_date >= subscription_start_date and subscription_start_date >= subscription_creation_date"
            name: "sub_end_date_not_before_start_date_not_before_create_date"
        - dbt_utils.expression_is_true: 
            expression: "term_month >= 0 and monthly_rate>= 0 and expected_total_subscription_value>= 0"
            name: "term_month_and_monthly_rating_positive"
        - dbt_utils.expression_is_true:
            expression: "defleet_date >= infleet_date"
            name: "defleet_not_before_infleet"
        - dbt_utils.expression_is_true:
            expression: "defleet_date >= subscription_start_date and subscription_start_date >= infleet_date"
            name: "start_between_infleet_defleet"
    columns:
      - name: subscription_id
        description: "Primary key for subscriptions"
        tests: [unique, not_null]
      - name: customer_id
        description: "Primary key for customers"
        tests: [not_null]
      - name: car_id
        description: "Primary key for cars"
        tests: [not_null]
      - name: subscription_creation_date
        description: "Subscription creation date"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type: {column_type: timestamp}
      - name: subscription_start_date
        description: "Subscription start date"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type: {column_type: timestamp}
      - name: subscription_end_date
        description: "Subscription end date"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type: {column_type: timestamp}
      - name: subscription_start_week_id
        description: "Week of the subscription start date (YYYY-WW format)"
        tests: 
          - not_null 
          - dbt_utils.expression_is_true:
              expression: " ~ '^\\d{4}-W\\d{2}$' = TRUE"
              name: "week_id_format_is_correct_final"
      - name: term_month 
        description: "Subscription length in months"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type: {column_type: integer} 
      - name: monthly_rate  
        description: "Monthly fee for the subscription"
        tests: 
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type: {column_type: double} 
      - name: expected_total_subscription_value
        description: "Subscription total cost value (monthly_rate * term_month)."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type: {column_type: double}
      - name: customer_type 
        description: "Customer classification (B2B/B2C)"
        tests: 
          - not_null
          - accepted_values:
              values: ['b2b', 'b2c']
              config:
                severity: error
      - name: address_city
        description: "Customer city address"
        tests: [not_null]
      - name: brand 
        description: "Vehicle Brand Name"
        tests: [not_null]
      - name: engine_type
        description: "Vehicle Engine Type"
        tests: [not_null]
      - name: model
        description: "Vehicle Model"
        tests: [not_null]
      - name: infleet_date
        description: "Date car was registered"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type: {column_type: timestamp}
      - name: defleet_date
        description: "Date car was deregistered; Future date if still registered"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type: {column_type: timestamp}