name: 'dbt_car_subscriptions'
version: '1.0.0'
config-version: 2

profile: 'dbt_car_subscriptions'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

